### ISSUE TITLE
Compiling on Windows

### ISSUE THREAD

**Issue by PlutusCN** [lindenb/cclindenb#3]
Some problems should be fixed when I compiled tarball.h and tarball.cpp on Windows 10 with Visual Studio 2015.
(1) Can't find '::getlogin()' and unistd.h on Windows
(2) std::snprintf(TARHEADER, 32, "%s", s) can't pass compilation

So, I have done:
(1) 
```
#if (defined _WIN32 || defined __WIN32__) && !defined __CYGWIN__
# define WIN32_LEAN_AND_MEAN
# include <windows.h>
const char* getlogin(void)
{
	static char user_name[MAX_PATH] = { 0 };
	DWORD length = sizeof(user_name);

	if (GetUserName(user_name, &length))
		return user_name;
	return nullptr;
}
#else
# include <unistd.h>
#endif
```
(2) 
	const char *s = ::getlogin();
	if (s)  std::snprintf(TARHEADER->uname, 32, "%s", s);

Hope that help sombody.

**Comment by lindenb** [comment]
:+1:
